/**
 * Xcode 27 (iOS 27 SDK) support for the prebuilt iOS project.
 *
 * Two things break when the app is built with the iOS 27 SDK:
 *
 * 1. UIKit terminates an app at launch unless it has adopted the scene-based
 *    life cycle (`UIApplicationEvaluateRuntimeIssueForNoSceneLifecycleAdoption`
 *    — see Apple TN3187). The Expo prebuild template still starts React Native
 *    from a window created in `application(_:didFinishLaunchingWithOptions:)`,
 *    so this plugin adds a `UIApplicationSceneManifest` to Info.plist and moves
 *    window creation into a `SceneDelegate`, mirroring `ExpoAppSceneDelegate`
 *    plus `SceneEventForwarder` (which expo ships from SDK 56 on). The scene
 *    delegate rebuilds the launch options that `Linking.getInitialURL()` reads
 *    from the scene's connection options — without that, a link that
 *    cold-starts the app reaches no one — and forwards every scene event
 *    (URLs, user activities, quick actions, life cycle) through the running
 *    \`ExpoAppDelegate\`, as upstream \`SceneEventForwarder\` does, and delivers
 *    links to React Native's linking manager exactly once. Delete the scene
 *    half of this plugin once the app moves to that SDK.
 *
 * 2. Xcode 27 rejects pod targets below iOS 15.0 (iosMath ships 6.0, RNSVG
 *    12.4), and `expo-router`'s iOS code uses iOS 16 APIs without an
 *    availability guard, so the pod targets must be raised to the app's own
 *    deployment target — `ios.deploymentTarget` in app.config.ts.
 *
 * Every mod below is idempotent and throws (instead of silently writing broken
 * Swift) when the prebuild template no longer matches the expected text.
 */
const {
  withAppDelegate,
  withInfoPlist,
  withPodfile,
} = require("expo/config-plugins");

/** Scene delegate class appended to the app delegate file. */
const SCENE_DELEGATE_CLASS = "SceneDelegate";

/** Marks scene delegate output as current; older generations lack it. */
const SCENE_DELEGATE_VERSION_MARKER = "Generated by withIosXcode27Support v4";
const PREVIOUS_SCENE_DELEGATE_VERSION_MARKER = "Generated by withIosXcode27Support v3";

/** Matches the window bootstrap block in the Expo AppDelegate template. */
const WINDOW_BOOTSTRAP = `#if os(iOS) || os(tvOS)
    window = UIWindow(frame: UIScreen.main.bounds)
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif`;

const SCENE_DELEGATE_SOURCE = `
/// Scene-based life cycle, which UIKit requires for apps built with the iOS 27
/// SDK. Mirrors \`ExpoAppSceneDelegate\` and \`SceneEventForwarder\` from Expo SDK 56
/// until the app can depend on them.
/// Generated by withIosXcode27Support v4.
class ${SCENE_DELEGATE_CLASS}: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(
    _ scene: UIScene,
    willConnectTo session: UISceneSession,
    options connectionOptions: UIScene.ConnectionOptions
  ) {
    guard let windowScene = scene as? UIWindowScene,
      let appDelegate = UIApplication.shared.delegate as? AppDelegate,
      let factory = appDelegate.reactNativeFactory
    else {
      fatalError("SceneDelegate couldn't start React Native: the app delegate exposes no factory.")
    }

    let window = UIWindow(windowScene: windowScene)
    self.window = window

    // Mirror the window onto the app delegate so code that reads
    // \`UIApplication.shared.delegate?.window\` keeps working.
    appDelegate.window = window

    // Under the scene life cycle UIKit passes cold-start URLs and activities in
    // \`connectionOptions\` instead of in the launch options. \`Linking.getInitialURL()\`
    // only reads launch options, so rebuild them here; otherwise a link that
    // cold-starts the app is delivered to no one, because the \`url\` event routed
    // below fires before JS is ready.
    let browsingWebActivity = connectionOptions.userActivities.first {
      $0.activityType == NSUserActivityTypeBrowsingWeb
    }
    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: ${SCENE_DELEGATE_CLASS}.launchOptions(
        url: connectionOptions.urlContexts.first?.url,
        userActivity: browsingWebActivity))

    // Forward cold-start links and activities as well: subscribers and
    // \`RCTLinkingManager\` may act on them before JS boots.
    connectionOptions.urlContexts.forEach {
      ${SCENE_DELEGATE_CLASS}.route(
        url: $0.url,
        options: ${SCENE_DELEGATE_CLASS}.openURLOptions(from: $0.options))
    }
    connectionOptions.userActivities.forEach { ${SCENE_DELEGATE_CLASS}.route(userActivity: $0) }

    // A quick action that cold-starts the app arrives here instead of in
    // \`windowScene(_:performActionFor:completionHandler:)\`, which UIKit only calls
    // while running.
    if let shortcutItem = connectionOptions.shortcutItem {
      appDelegate.application(
        UIApplication.shared,
        performActionFor: shortcutItem,
        completionHandler: { _ in })
    }
  }

  func sceneDidDisconnect(_ scene: UIScene) {
    window = nil
  }

  // UIKit no longer calls the app delegate equivalents under the scene life
  // cycle, so forward each event through the running \`ExpoAppDelegate\` —
  // upstream \`SceneEventForwarder\`'s boundary — so overrides on it keep
  // firing and the subscribers are reached by its own forwarding.

  func sceneDidBecomeActive(_ scene: UIScene) {
    ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.applicationDidBecomeActive(UIApplication.shared)
  }

  func sceneWillResignActive(_ scene: UIScene) {
    ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.applicationWillResignActive(UIApplication.shared)
  }

  func sceneWillEnterForeground(_ scene: UIScene) {
    ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.applicationWillEnterForeground(UIApplication.shared)
  }

  func sceneDidEnterBackground(_ scene: UIScene) {
    ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.applicationDidEnterBackground(UIApplication.shared)
  }

  func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
    // React Native ignores the app-delegate URL API under the scene life cycle,
    // so a warm link only reaches JS through the scene API.
    URLContexts.forEach {
      ${SCENE_DELEGATE_CLASS}.route(
        url: $0.url,
        options: ${SCENE_DELEGATE_CLASS}.openURLOptions(from: $0.options))
    }
  }

  func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
    ${SCENE_DELEGATE_CLASS}.route(userActivity: userActivity)
  }

  func scene(_ scene: UIScene, willContinueUserActivityWithType userActivityType: String) {
    // The scene callback returns \`Void\`; the \`Bool\` belongs to the
    // app-delegate callback. A \`-> Bool\` here stops Swift from matching the
    // optional protocol requirement, so UIKit would never call this method.
    _ = ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.application(
      UIApplication.shared,
      willContinueUserActivityWithType: userActivityType)
  }

  func scene(
    _ scene: UIScene,
    didFailToContinueUserActivityWithType userActivityType: String,
    error: Error
  ) {
    ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.application(
      UIApplication.shared,
      didFailToContinueUserActivityWithType: userActivityType,
      error: error)
  }

  func scene(_ scene: UIScene, didUpdate userActivity: NSUserActivity) {
    ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.application(UIApplication.shared, didUpdate: userActivity)
  }

  func windowScene(
    _ windowScene: UIWindowScene,
    performActionFor shortcutItem: UIApplicationShortcutItem,
    completionHandler: @escaping (Bool) -> Void
  ) {
    ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.application(
      UIApplication.shared,
      performActionFor: shortcutItem,
      completionHandler: completionHandler)
  }

  // MARK: - Forwarding

  /// The running app delegate typed as \`ExpoAppDelegate\`. Scene events go
  /// through it — upstream \`SceneEventForwarder\`'s boundary — so overrides on
  /// it keep firing while the base class still forwards to the subscribers.
  private static var expoAppDelegate: ExpoAppDelegate? {
    UIApplication.shared.delegate as? ExpoAppDelegate
  }

  /// Routes a URL through the app delegate — subscribers and any
  /// \`ExpoAppDelegate\` override — then to React Native's linking manager
  /// unless it was already delivered. Both feed expo-router's incoming-link
  /// handling, and a double call would deliver two JS \`url\` events for one
  /// link.
  private static func route(url: URL, options: [UIApplication.OpenURLOptionsKey: Any]) {
    let observer = LinkingManagerObserver(url: url)
    _ = ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.application(UIApplication.shared, open: url, options: options)
    if !observer.wasNotified {
      _ = RCTLinkingManager.application(UIApplication.shared, open: url, options: options)
    }
  }

  /// Routes a universal link (or other user activity) through the app
  /// delegate and React Native's linking manager. \`RCTLinkingManager\` only announces
  /// browsing-web activities, so the deduplication only applies to those.
  private static func route(userActivity: NSUserActivity) {
    let observer = userActivity.webpageURL.map { LinkingManagerObserver(url: $0) }
    _ = ${SCENE_DELEGATE_CLASS}.expoAppDelegate?.application(
      UIApplication.shared,
      continue: userActivity,
      restorationHandler: { _ in })
    if observer?.wasNotified != true {
      _ = RCTLinkingManager.application(
        UIApplication.shared,
        continue: userActivity,
        restorationHandler: { _ in })
    }
  }

  /// Maps scene URL options onto the app-delegate options that subscribers and
  /// \`RCTLinkingManager\` expect.
  private static func openURLOptions(
    from sceneOptions: UIScene.OpenURLOptions
  ) -> [UIApplication.OpenURLOptionsKey: Any] {
    var options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    if let sourceApplication = sceneOptions.sourceApplication {
      options[.sourceApplication] = sourceApplication
    }
    if let annotation = sceneOptions.annotation {
      options[.annotation] = annotation
    }
    options[.openInPlace] = sceneOptions.openInPlace
    return options
  }

  /// Rebuilds the launch options that \`Linking.getInitialURL()\` reads from a
  /// scene's connection options. Returns \`nil\` when the app was not cold-started
  /// by a URL or a browsing-web activity, so it can be forwarded to
  /// \`startReactNative\` as-is.
  private static func launchOptions(
    url: URL?,
    userActivity: NSUserActivity?
  ) -> [UIApplication.LaunchOptionsKey: Any]? {
    // Build the keys from their underlying constant strings: the typed
    // accessors are deprecated as of iOS 26, but React Native still reads the
    // launch options by these exact keys, so this is the shape it expects.
    var launchOptions: [UIApplication.LaunchOptionsKey: Any] = [:]
    if let url {
      let urlKey = UIApplication.LaunchOptionsKey(rawValue: "UIApplicationLaunchOptionsURLKey")
      launchOptions[urlKey] = url
    }
    if let userActivity {
      let activityDictionaryKey = UIApplication.LaunchOptionsKey(
        rawValue: "UIApplicationLaunchOptionsUserActivityDictionaryKey")
      launchOptions[activityDictionaryKey] = [
        "UIApplicationLaunchOptionsUserActivityTypeKey": userActivity.activityType,
        "UIApplicationLaunchOptionsUserActivityKey": userActivity,
      ]
    }
    return launchOptions.isEmpty ? nil : launchOptions
  }
}

/// Observes the notification \`RCTLinkingManager\` posts for every link it
/// handles, so forwarding can skip a link that already reached React Native.
/// The notification name is private to React Native; expo-router spells it out
/// the same way. If React Native renames it, the worst case is a duplicate
/// \`url\` event — a link is never lost.
private final class LinkingManagerObserver: NSObject {
  private let expectedURL: String
  private(set) var wasNotified = false

  init(url: URL) {
    expectedURL = url.absoluteString
    super.init()
    NotificationCenter.default.addObserver(
      self,
      selector: #selector(linkingManagerDidOpenURL(_:)),
      name: Notification.Name("RCTOpenURLNotification"),
      object: nil
    )
  }

  deinit {
    NotificationCenter.default.removeObserver(self)
  }

  @objc
  private func linkingManagerDidOpenURL(_ notification: Notification) {
    wasNotified = wasNotified || notification.userInfo?["url"] as? String == expectedURL
  }
}
`;

/** Builds the scene manifest so UIKit adopts the scene-based life cycle. */
function buildSceneManifest() {
  return {
    UIApplicationSupportsMultipleScenes: false,
    UISceneConfigurations: {
      UIWindowSceneSessionRoleApplication: [
        {
          UISceneConfigurationName: "Default",
          UISceneDelegateClassName: `$(PRODUCT_MODULE_NAME).${SCENE_DELEGATE_CLASS}`,
        },
      ],
    },
  };
}

/** Adds the scene manifest so UIKit adopts the scene-based life cycle. */
function applySceneManifest(infoPlist) {
  infoPlist.UIApplicationSceneManifest = buildSceneManifest();
  return infoPlist;
}

/**
 * Moves window creation out of the app delegate and appends the scene
 * delegate. Idempotent; throws when the template no longer matches.
 */
function applySceneDelegate(appDelegateContents) {
  let contents = appDelegateContents;

  if (contents.includes(`class ${SCENE_DELEGATE_CLASS}:`)) {
    // `expo prebuild` on an existing ios/ directory re-runs the mods against
    // the existing files, so the guard below must distinguish the current
    // generation from output written by an older plugin version — silently
    // keeping stale generated Swift would freeze the old behavior in place.
    if (contents.includes(SCENE_DELEGATE_VERSION_MARKER)) {
      return contents;
    }
    if (contents.includes(PREVIOUS_SCENE_DELEGATE_VERSION_MARKER)) {
      const markerIndex = contents.indexOf(PREVIOUS_SCENE_DELEGATE_VERSION_MARKER);
      return (
        contents.slice(0, markerIndex) +
        contents
          .slice(markerIndex)
          .replace(PREVIOUS_SCENE_DELEGATE_VERSION_MARKER, SCENE_DELEGATE_VERSION_MARKER)
          .replaceAll(
            "expoAppDelegate?",
            `${SCENE_DELEGATE_CLASS}.expoAppDelegate?`,
          )
      );
    }
    throw new Error(
      "withIosXcode27Support found a " +
        SCENE_DELEGATE_CLASS +
        " generated by an older version of the plugin. Delete apps/mobile/ios (or run " +
        "`pnpm exec expo prebuild -p ios --clean`) and prebuild again.",
    );
  }
  if (!contents.includes(WINDOW_BOOTSTRAP)) {
    throw new Error(
      "withIosXcode27Support could not find the window bootstrap block in the app delegate " +
        "template. The Expo template changed — update WINDOW_BOOTSTRAP in " +
        "apps/mobile/plugins/withIosXcode27Support.js.",
    );
  }

  contents = contents.replace(
    WINDOW_BOOTSTRAP,
    "    // The window is created by SceneDelegate.scene(_:willConnectTo:); UIKit requires\n" +
      "    // the scene-based life cycle for apps built with the iOS 27 SDK.",
  );
  contents = `${contents.trimEnd()}\n${SCENE_DELEGATE_SOURCE}`;

  return contents;
}

/**
 * Raises every pod target to the app's deployment target. Xcode 27 rejects
 * targets below iOS 15.0, and modules such as expo-router need iOS 16 APIs.
 */
function applyPodDeploymentTarget(podfileContents) {
  let contents = podfileContents;

  if (contents.includes("min_deployment_target")) {
    return contents;
  }

  const postInstall = contents.match(
    /post_install do \|installer\|[\s\S]*?\n  end\n/,
  );
  if (!postInstall) {
    throw new Error(
      "withIosXcode27Support could not find the Podfile post_install hook. The Expo Podfile " +
        "template changed — update the anchor in apps/mobile/plugins/withIosXcode27Support.js.",
    );
  }

  const bump = [
    "    # Xcode 27 rejects pod targets below iOS 15.0 (iosMath ships 6.0, RNSVG",
    "    # 12.4) and expo-router's iOS code needs iOS 16 APIs, so raise every pod",
    "    # target to the app's deployment target.",
    "    min_deployment_target = podfile_properties['ios.deploymentTarget'] || '16.0'",
    "    installer.pods_project.targets.each do |target|",
    "      target.build_configurations.each do |config|",
    "        current = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']",
    "        next unless current.to_s =~ /\\A\\d/",
    "        if Gem::Version.new(current) < Gem::Version.new(min_deployment_target)",
    "          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_deployment_target",
    "        end",
    "      end",
    "    end",
    "",
  ].join("\n");

  contents = contents.replace(
    postInstall[0],
    postInstall[0].replace(/\n  end\n$/, `\n${bump}  end\n`),
  );

  return contents;
}

/** Adds the scene manifest so UIKit adopts the scene-based life cycle. */
function withSceneManifest(config) {
  return withInfoPlist(config, (config) => {
    config.modResults = applySceneManifest(config.modResults);
    return config;
  });
}

/** Moves window creation out of the app delegate and appends the scene delegate. */
function withSceneDelegate(config) {
  return withAppDelegate(config, (config) => {
    if (config.modResults.language !== "swift") {
      throw new Error(
        "withIosXcode27Support expects the Swift app delegate template; found " +
          `"${config.modResults.language}".`,
      );
    }

    config.modResults.contents = applySceneDelegate(config.modResults.contents);
    return config;
  });
}

function withPodDeploymentTarget(config) {
  return withPodfile(config, (config) => {
    config.modResults.contents = applyPodDeploymentTarget(
      config.modResults.contents,
    );
    return config;
  });
}

module.exports = function withIosXcode27Support(config) {
  config = withSceneManifest(config);
  config = withSceneDelegate(config);
  config = withPodDeploymentTarget(config);
  return config;
};

// Pure transforms, exported for regression tests.
module.exports.applySceneManifest = applySceneManifest;
module.exports.applySceneDelegate = applySceneDelegate;
module.exports.applyPodDeploymentTarget = applyPodDeploymentTarget;
